module.exports = {
    styles: {
        '_alert': true,
        '_animation': true,
        '_breadcrumb': true,
        '_button-group': true,
        '_buttons': true,
        '_card': true,
        '_carousel': true,
        '_close': true,
        '_code': true,
        '_custom-forms': true,
        '_dropdown': true,
        '_forms': true,
        '_grid': true,
        '_images': true,
        '_input-group': true,
        '_jumbotron': true,
        '_labels': true,
        '_list-group': true,
        '_media': true,
        '_mixins': true,
        '_modal': true,
        '_nav': true,
        '_navbar': true,
        '_normalize': true,
        '_pager': true,
        '_pagination': true,
        '_popover': true,
        '_print': true,
        '_progress': true,
        '_reboot': true,
        '_responsive-embed': true,
        '_tables': true,
        '_tooltip': true,
        '_type': true,
        '_utilities-responsive': true,
        '_utilities-spacing': true,
        '_utilities': true,
        '_variables': true
    }
};

